workflows:
  ios-capacitor:
    name: Build iOS SGOS

    instance_type: mac_mini_m2

    environment:
      node: latest

    scripts:
      - npm install
      - npm install @capacitor/ios
      - npx cap add ios || true
      - npx cap sync ios
      - cd ios/App
      - pod install
      - xcodebuild \
          -workspace App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO

    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.app