plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace "com.sgos.mobile"
    compileSdk 36

    defaultConfig {
        applicationId "com.sgos.mobile"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'com.google.firebase:firebase-messaging:24.1.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}

apply from: 'capacitor.build.gradle'
